#Requires -Version 5.1
<#
.SYNOPSIS
  นำเข้า tbmenu + tbworkcenter จาก MySQL sap_lay → SQL สำหรับ PostgreSQL (app schema)

.DESCRIPTION
  อ่านการเชื่อมต่อจาก sap/include/connection.php
  สร้างไฟล์:
    database/seeds/generated/import_tbmenu_pg.sql
    database/seeds/generated/import_tbworkcenter_pg.sql

  ต้องมี mysql.exe ใน PATH

  ตัวอย่าง:
    pwsh -File database/scripts/import-auth-from-mysql.ps1
    psql "postgresql://pepsipm:PASS@127.0.0.1:5433/pepsi_pm" -v ON_ERROR_STOP=1 -f database/seeds/generated/import_tbmenu_pg.sql
#>

$ErrorActionPreference = 'Stop'
$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$ConnPhp = Join-Path $RepoRoot 'sap\include\connection.php'
$OutDir = Join-Path $RepoRoot 'database\seeds\generated'
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

if (-not (Test-Path $ConnPhp)) { Write-Error "Not found: $ConnPhp" }

$content = Get-Content -Raw -Path $ConnPhp
function Get-PhpString($key) {
  if ($content -match "\`$GLOBALS\[`"$key`"\]\s*=\s*`"([^`"]+)`) { return $Matches[1] }
  return $null
}

$hostName = Get-PhpString 'host'
$user = Get-PhpString 'Uname'
$pass = Get-PhpString 'Pword'
$db = Get-PhpString 'DBName'

$mysql = Get-Command mysql -ErrorAction SilentlyContinue
if (-not $mysql) {
  Write-Error 'mysql client not in PATH. Install MySQL client or add to PATH.'
}

function Escape-Sql($s) {
  if ($null -eq $s) { return 'NULL' }
  return "'" + ($s -replace "'", "''") + "'"
}

function Map-ReactRoute($menulink) {
  if ([string]::IsNullOrWhiteSpace($menulink)) { return $null }
  $raw = $menulink.Trim()
  if ($raw.StartsWith('/')) { return ($raw -split '\?')[0] }
  if ($raw -match '[?&]module=([A-Za-z0-9_]+)') {
    $mod = $Matches[1].ToLower()
    $map = @{
      'calendar' = '/calendar'
      'line_calendar' = '/line-calendar'
      'backlog' = '/backlog'
      'workorder' = '/work-orders'
      'm_confirmation' = '/confirmation'
      'm_planwork_view' = '/planning'
      'm_iw37n' = '/iw37n'
      'm_activitytype' = '/master-data'
      'm_manhour' = '/manhours'
      'w_worktime_view' = '/worktime'
      'm_personel' = '/personnel'
      'w_manhours_hr' = '/manhours-hr'
      'w_summary_weekly' = '/summary-weekly'
      'user' = '/settings'
      'content' = '/'
      'info' = '/'
    }
    if ($map.ContainsKey($mod)) { return $map[$mod] }
  }
  return $null
}

function Run-MysqlQuery($sql) {
  $args = @("-h$hostName", "-u$user", "-p$pass", $db, "-N", "-B", "-e", $sql)
  $out = & mysql @args 2>&1
  if ($LASTEXITCODE -ne 0) { throw "mysql failed: $out" }
  return $out
}

Write-Host "Exporting tbmenu from MySQL $db @ $hostName ..."

$menuRows = Run-MysqlQuery @"
SELECT idmenu, IFNULL(idmenusub,'0'), IFNULL(menuon,0),
       IFNULL(menuright,'A'), IFNULL(menuicon,''),
       IFNULL(menutitle,''), IFNULL(menulink,''),
       IFNULL(menuname,''), IFNULL(menulavel,1)
FROM tbmenu
ORDER BY menuon, idmenu
"@

$menuSql = @(
  '-- Generated by import-auth-from-mysql.ps1 — รัน on PostgreSQL pepsi_pm',
  'BEGIN;',
  'DELETE FROM app.tbmenu;',
  ''
)

$maxId = 0
foreach ($line in $menuRows) {
  if ([string]::IsNullOrWhiteSpace($line)) { continue }
  $cols = $line -split "`t"
  if ($cols.Count -lt 9) { continue }
  $idmenu = [int]$cols[0]
  if ($idmenu -gt $maxId) { $maxId = $idmenu }
  $idmenusub = $cols[1]
  $menuon = [int]$cols[2]
  $menuright = $cols[3]
  $menuicon = $cols[4]
  $menutitle = $cols[5]
  $menulink = $cols[6]
  $menuname = $cols[7]
  $menulavel = [int]$cols[8]
  $react = Map-ReactRoute $menulink
  $kind = if ($menulavel -eq 1 -and $react) { 'item' } elseif ($idmenusub -eq '0' -and -not $react) { 'heading' } else { 'item' }
  $endExact = if ($react -eq '/') { 'true' } else { 'false' }
  $menuSql += "INSERT INTO app.tbmenu (idmenu, idmenusub, menuon, menu_kind, menuright, menuicon, menutitle, menulink, react_route, menuname, menulavel, end_exact) VALUES ($idmenu, $(Escape-Sql $idmenusub), $menuon, $(Escape-Sql $kind), $(Escape-Sql $menuright), $(Escape-Sql $menuicon), $(Escape-Sql $menutitle), $(Escape-Sql $menulink), $(if ($react) { Escape-Sql $react } else { 'NULL' }), $(Escape-Sql $menuname), $menulavel, $endExact);"
}

$menuSql += ''
$menuSql += "SELECT setval(pg_get_serial_sequence('app.tbmenu', 'idmenu'), $maxId);"
$menuSql += 'COMMIT;'

$menuPath = Join-Path $OutDir 'import_tbmenu_pg.sql'
$menuSql | Set-Content -Path $menuPath -Encoding UTF8
Write-Host "Wrote $menuPath ($($menuRows.Count) rows)"

Write-Host "Exporting tbworkcenter ..."

$wcRows = Run-MysqlQuery @"
SELECT idwkctr, pass, wkctr, IFNULL(plnt,''), IFNULL(wkctrdate,0), IFNULL(startwork,0),
       IFNULL(titlewkctr,''), IFNULL(namewkctr,''), IFNULL(surnamewkctr,''),
       IFNULL(titlewkctreng,''), IFNULL(namewkctreng,''), IFNULL(surnamewkctreng,''),
       IFNULL(idwkctrgroup,''), IFNULL(idwkctrtype,''), IFNULL(idposition,''), IFNULL(iddepartment,''),
       IFNULL(userst,'U'), IFNULL(imgmember,'')
FROM tbworkcenter
"@

$wcSql = @(
  '-- Generated by import-auth-from-mysql.ps1',
  'BEGIN;',
  ''
)

foreach ($line in $wcRows) {
  if ([string]::IsNullOrWhiteSpace($line)) { continue }
  $c = $line -split "`t"
  if ($c.Count -lt 16) { continue }
  $wcSql += @"
INSERT INTO app.tbworkcenter (
  idwkctr, pass, wkctr, plnt, wkctrdate, startwork,
  titlewkctr, namewkctr, surnamewkctr, titlewkctreng, namewkctreng, surnamewkctreng,
  idwkctrgroup, idwkctrtype, idposition, iddepartment, userst, imgmember
) VALUES (
  $(Escape-Sql $c[0]), $(Escape-Sql $c[1]), $(Escape-Sql $c[2]), $(Escape-Sql $c[3]),
  $($c[4]), $($c[5]),
  $(Escape-Sql $c[6]), $(Escape-Sql $c[7]), $(Escape-Sql $c[8]),
  $(Escape-Sql $c[9]), $(Escape-Sql $c[10]), $(Escape-Sql $c[11]),
  $(Escape-Sql $c[12]), $(Escape-Sql $c[13]), $(Escape-Sql $c[14]), $(Escape-Sql $c[15]),
  $(Escape-Sql $c[16]), $(if ($c.Count -gt 17) { Escape-Sql $c[17] } else { 'NULL' })
) ON CONFLICT (idwkctr) DO UPDATE SET
  pass = EXCLUDED.pass, wkctr = EXCLUDED.wkctr, plnt = EXCLUDED.plnt,
  userst = EXCLUDED.userst;
"@
}

$wcSql += 'COMMIT;'
$wcPath = Join-Path $OutDir 'import_tbworkcenter_pg.sql'
$wcSql | Set-Content -Path $wcPath -Encoding UTF8
Write-Host "Wrote $wcPath ($($wcRows.Count) rows)"
Write-Host 'Done. Run both .sql files in DBeaver against pepsi_pm (schema app).'
