/** Authenticated routes for full-app console / crash audit (admin as ADMIN01). */
export const ALL_APP_ROUTES: Array<{ path: string; label: string }> = [
  { path: '/portal', label: 'portal' },
  { path: '/', label: 'home' },
  { path: '/plan-calendar', label: 'plan-calendar' },
  { path: '/calendar', label: 'calendar' },
  { path: '/backlog', label: 'backlog' },
  { path: '/work-orders', label: 'work-orders' },
  { path: '/pm-vibration', label: 'pm-vibration' },
  { path: '/confirmation', label: 'confirmation' },
  { path: '/planning', label: 'planning' },
  { path: '/integration', label: 'integration' },
  { path: '/iw37n', label: 'iw37n' },
  { path: '/master-plan', label: 'master-plan' },
  { path: '/master-data', label: 'master-data' },
  { path: '/manhours', label: 'manhours' },
  { path: '/worktime', label: 'worktime' },
  { path: '/personnel', label: 'personnel' },
  { path: '/personnel/confirm', label: 'personnel-confirm' },
  { path: '/reports', label: 'reports' },
  { path: '/reports/audit', label: 'auditor-hub' },
  { path: '/activity-log', label: 'activity-log' },
  { path: '/manhours-hr', label: 'manhours-hr' },
  { path: '/summary-weekly', label: 'summary-weekly' },
  { path: '/user-log', label: 'user-log' },
  { path: '/settings', label: 'settings' },
  { path: '/admin', label: 'admin-console' },
  { path: '/admin/branding', label: 'admin-branding' },
  { path: '/admin/settings', label: 'admin-settings' },
  { path: '/admin/master', label: 'admin-master' },
  { path: '/admin/audit', label: 'admin-audit' },
  { path: '/admin/health', label: 'admin-health' },
  { path: '/admin/backup', label: 'admin-backup' },
  { path: '/admin/announcements', label: 'admin-announcements' },
  { path: '/admin/telegram', label: 'admin-telegram' },
  { path: '/admin/security', label: 'admin-security' },
  { path: '/admin/about', label: 'admin-about' },
  { path: '/admin/users', label: 'admin-users' },
  { path: '/admin/roles', label: 'admin-roles' },
  { path: '/admin/menu', label: 'admin-menu' },
  { path: '/board', label: 'engineering-board' },
]

